services:
  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "ae89cbd1-1873-40b4-aca2-496f5307f214"

      ADMIN_EMAIL: "sonnv1912@gmail.com"
      ADMIN_PASSWORD: "11111111"

      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"

      WEBSOCKETS_ENABLED: "true"

      CORS_ENABLED: "true"
